version: "3.8"

services:
  mongo:
    image: mongo
    container_name: blog-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27018:27017
    volumes:
      - blog:/data/db
    networks:
      - blog-network

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    networks:
      - blog-network
    depends_on:
      - mongo

  rabbitmq:
    image: "rabbitmq:latest"
    container_name: blog-rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    # environment:
    #   RABBITMQ_DEFAULT_USER: user
    #   RABBITMQ_DEFAULT_PASS: password
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - blog-network

  userauthservice:
    build: ./backend/services/userAuthService
    container_name: blog-user-auth-service
    image: jitheshmjithooz/blog-user-auth-service
    restart: unless-stopped
    env_file:
      - ./backend/services/userAuthService/.env
    ports:
      - 3000:3000
    networks: 
      - blog-network
    develop:
      watch:
        - action: sync
          path: ./backend/services/userAuthService
          target: /app/
          ignore:
            - node_modules/
        - action: rebuild
          path: ./backend/services/userAuthService/package.json
    depends_on:
      - mongo
      - rabbitmq

  postservice:
    build: ./backend/services/postService
    container_name: blog-post-service
    image: jitheshmjithooz/blog-post-service
    restart: unless-stopped
    env_file:
      - ./backend/services/postService/.env
    ports:
      - 3001:3001
    networks: 
      - blog-network
    develop:
      watch:
        - action: sync
          path: ./backend/services/postService
          target: /app/
          ignore:
            - node_modules/
        - action: rebuild
          path: ./backend/services/postService/package.json
    depends_on:
      - mongo
      - rabbitmq

  commentservice:
    build: ./backend/services/commentService
    container_name: blog-comment-service
    image: jitheshmjithooz/blog-comment-service
    restart: unless-stopped
    env_file:
      - ./backend/services/commentService/.env
    ports:
      - 3002:3002
    networks: 
      - blog-network
    develop:
      watch:
        - action: sync
          path: ./backend/services/commentService
          target: /app/
          ignore:
            - node_modules/
        - action: rebuild
          path: ./backend/services/commentService/package.json
    depends_on:
      - mongo
      - rabbitmq

  notificationservice:
    build: ./backend/services/notificationService
    container_name: blog-notification-service
    image: jitheshmjithooz/blog-notification-service
    restart: unless-stopped
    env_file:
      - ./backend/services/notificationService/.env
    ports:
      - 3003:3003
    networks: 
      - blog-network
    develop:
      watch:
        - action: sync
          path: ./backend/services/notificationService
          target: /app/
          ignore:
            - node_modules/
        - action: rebuild
          path: ./backend/services/notificationService/package.json
    depends_on:
      - mongo
      - rabbitmq


  user-frontend:
    build: ./frontend/user
    container_name: blog-user-frontend
    image: jitheshmjithooz/blog-user-frontend
    restart: unless-stopped
    env_file:
      - ./frontend/user/.env
    ports:
      - 2000:3000
    networks: 
      - blog-network
    develop:
      watch:
        - action: sync
          path: ./frontend/user
          target: /app/
          ignore:
            - node_modules/
        - action: rebuild
          path: ./frontend/user/package.json
    depends_on:
      - mongo
      - userauthservice

  nginx:
    build: ./backend/gateway
    container_name: blog-nginx
    image: jitheshmjithooz/blog-gateway
    ports:
      - 8000:80
    networks:
      - blog-network
    depends_on:
      - userauthservice
      - postservice
      - commentservice




volumes:
  blog:


networks:
  blog-network:
    driver: bridge
