import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>

        <link rel="stylesheet" href="/vendor.css" />

        <link rel="stylesheet" href="/responsive.css" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" />



      </head>
      <body className={inter.className}>
        {children}
        <script src="/js/vendor.js"></script>

        <script src="/js/main.js"></script>
      </body>

    </html>
  );
}
